// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package provider

import (
	"github.com/rkrohk/moviehall/pkg/queue"
)

// Injectors from publisher_provider.go:

func NewPublisher(config *queue.ConnectionConfig) queue.Publisher {
	connection := queue.NewConnection(config)
	channel := queue.NewChannel(connection)
	rabbitMQPublisher := queue.NewPublisher(channel)
	return rabbitMQPublisher
}
