---
version: '3'
services:

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq

  server:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    command: /bin/sh -c "while sleep 1000; do :; done"
